### ISSUE TITLE
Google Maps API Missing on the Website?

### ISSUE THREAD

**Issue by amithvasantha** [RuurdBijlsma/locationestimatr2#1]
If you load up any map on the website, the Street View and map are all watermarked with "For development purposes only." There's also a popup on both windows saying "This page can't load Google Maps correctly." I searched up the error message and apparently these messages mean the API key is missing.
[Relevant Stack Overflow Link](https://stackoverflow.com/questions/50977913/google-maps-shows-for-development-purposes-only)
[Relevant Google Maps Help Link](https://developers.google.com/maps/documentation/javascript/error-messages?utm_source=maps_js&utm_medium=degraded&utm_campaign=billing#api-key-and-billing-errors)
![image](https://user-images.githubusercontent.com/20146609/79789408-fb70d000-82fe-11ea-8a78-3df7dd743e47.png)

**Comment by RuurdBijlsma** [comment]
Yea the api key I had was disabled, I had a transitional billing account for it but that was somehow closed without much explaination. I can't make a new api key because I have no credit card, also it would cost money when the free quota is reached. So there isn't much I can do. I've been thinking about making a self host tutorial, but it's very long as the project integrates a lot with Firebase which needs a lot of setup

**Comment by RuurdBijlsma** [comment]
api key issue is fixed now
